//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int ID { get; set; }
        [Required(ErrorMessage="Nhập UserName", AllowEmptyStrings=false)]
        public string UserCode { get; set; }
        [Required(ErrorMessage = "Nhập Password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50,MinimumLength=8, ErrorMessage="8 ký tự")]
        public string Pass { get; set; }
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string PassConfirm{ get; set; }

        [Required(ErrorMessage = "Nhập FullName", AllowEmptyStrings = false)]
        public string FullName { get; set; }
    }
}
